server:
  port: 8080
debug:
  false
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${spring.datasource.driver-class-name}
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  #mapper config
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rrobinvip.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      rrobinvip:
        mapper: debug
        service: info
        controller: info

employee:
  jwt:
    # JWT token secret key
    admin-secret-key: ${employee.jwt.admin-secret-key}
    # JWT token expire time (ms)
    admin-ttl: ${employee.jwt.admin-ttl}
    # Token name passed from request
    admin-token-name: ${employee.jwt.admin-token-name}

cloud:
  aws:
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
      bucket-name: ${cloud.aws.credentials.bucket-name}
      end-point: ${cloud.aws.credentials.end-point}